---
# tasks file for haproxy
- name: haproxy install
  yum:
            name: haproxy
            state: installed

- name: copy web 
  template: 
               src: haproxy.cfg
               dest: /etc/haparoxy/haproxy.cfg
  notify: lb restart


- name: start haproxy service
  service:
          name: haproxy
          state: started
